(ns bracketbird.components.settings-tab
  (:require [bracketbird.components.tournament-tab-content :as tab-content]
            [bracketbird.state :as state]
            [bracketbird.styles :as s]))


(defn content [ctx]
  [:div {:style s/tournamet-tab-content-style}
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "ccc"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "xxxx"]
   ])

(defn render [ctx]
  [content ctx])