(ns bracketbird.pages.settings-tab
  (:require [bracketbird.pages.tournament-tab-content :as tab-content]))


(defn content [ctx]
  [:div
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "ccc"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "settings-ssss"]
   [:div "xxxx"]
   ])

(defn render [ctx]
  [tab-content/render ctx [content ctx]])